### PR TITLE
Condition Rework

### PR DESCRIPTION
**Pull request by maxence-charriere**
Conditon now takes a function that returns UI elements instead of a list of UI elements.

### CODE REVIEW

**Comment by oderwat** [comment]
Why all those strange special functions if you can just use an on inline function and have much easier to read code in the end too?

**Comment by maxence-charriere** [comment]
## Why use specialized functions like `app.If` instead of just using inline functions?

Let's compare the two approaches to see the advantages of using `app.If`.

### Inline Function Approach:

Using an inline function for conditional rendering could look like this:

```go
func testFunc() app.UI {
	return app.Div().Body(
		func() app.UI {
			if true {
				return app.H1().Text("hello")
			}
			return nil
		}(),
	)
}
```

- **Drawbacks**:
  - Takes 5 lines to achieve an `if` condition.
  - Requires handling what happens when the condition is not met.

### Using `app.If`:

With the specialized `app.If`, the code becomes more concise and expressive:

```go
func testFunc() app.UI {
	return app.Div().Body(
		app.If(true, func() []app.UI {
			return app.H1().Text("hello")
		}),
	)
}
```

- **Advantages**:
  - Reduces the code to 3 lines for an `if` condition.
  - Handles `Else` or `ElseIf` only when necessary.
  - Benefits from auto-complete features in text editors due to the function signature.

### Additional Considerations:

- **API and Discoverability**: The `app.If` function is more discoverable and intuitive than using an inline function for new users or those who are not familiar with the possibility of using inline functions for this purpose.

- **Migration Experience**: For developers migrating from an older version, encountering a compiler error on the previous `if` structure will direct them to the new `app.If`, which is more straightforward to adapt to.

**Comment by maxence-charriere** [comment]
Let's also add that having `app.If` does not prevent you from using the inline version if you prefer it. The choice is yours.

**Comment by oderwat** [comment]
> Let's also add that having `app.If` does not prevent you from using the inline version if you prefer it. The choice is yours.

Yes, I think my views about it are not really relevant. I do not like this chaining, all the additional functions and the resulting overhead with many different inline functions. But if you think it is a valid API you want to support, go for it.

**Comment by maxence-charriere** [comment]
Hey @oderwat,

I was able to read your deleted response and I understand your perspective.

Another motivation behind creating app.If is to address the challenge of inlining a function that returns multiple UI elements. When dealing with a slice, it must be passed into app.Range and evaluated beforehand. This renders the use of the inline function impractical for that scenario.

**Pull request merged**
