### PR TITLE
Elem refactoring and customizable element

### PR DESCRIPTION
**Pull request by maxence-charriere**
## Summary

- update requirement to go 1.18
- elem refactoring
  - Now have a `On` method to set arbitrary event handlers
  - Internal code better organized and tested
  - optimized html writing
- customizable element
- customizable self closing element

## Notes

- I initially wanted to use generics for this refactoring but it doubled the size of the wasm binary, which is not acceptable.
- I bumped the go version because there are other areas than generics that I want to use.
- The customizable part is inspired by @oderwat https://github.com/maxence-charriere/go-app/pull/622
- I did not include any xmlns constant since I don't want this package to be a dictionary of xmlns

## Testing
- This is working on my projects
- I would love to have some feedbacks. @oderwat the elems are `Customizable` and `SelfClosingCustomizable`.

### CODE REVIEW

**Comment by oderwat** [comment]
Hi Maxence, I will look into it soon and try to compile my projects and adjust my framework for that too. 

We need the other PRs of mine for our projects so I may end up with quite some work (don't know how good they will merge). 

Could you give me an example of how to create custom Elements like the ones in my PR?

The result needs to be something our code generator could create from raw HTML that ends up looking like that:

```go
app.Div().Body(
  app.Elem("svg").XMLNS("http://www.w3.org/2000/svg").Class("icon", "icon-tabler",
    "icon-tabler-arrow-narrow-right").Attr("width", "24").Attr("height", "24").Attr("viewBox", "0 0 24 24").
    Attr("stroke-width", "1.5").Attr("stroke", "#4338CA").Attr("fill", "none").Attr("stroke-linecap", "round").
    Attr("stroke-linejoin", "round").Body(
    app.Elem("path").XMLNS("http://www.w3.org/2000/svg").Attr("stroke", "none").Attr("d", "M0 0h24v24H0z").Attr("fill", "none"),
    app.Elem("line").XMLNS("http://www.w3.org/2000/svg").Attr("x1", "5").Attr("y1", "12").Attr("x2", "19").Attr("y2", "12"),
    app.Elem("line").XMLNS("http://www.w3.org/2000/svg").Attr("x1", "15").Attr("y1", "16").Attr("x2", "19").Attr("y2", "12"),
    app.Elem("line").XMLNS("http://www.w3.org/2000/svg").Attr("x1", "15").Attr("y1", "8").Attr("x2", "19").Attr("y2", "12"),
  ),
 ),
```

I also noticed the benchmark output (element mounting?). I would not find any "reworked" code valuable that makes go-app slower or creates bigger executables. I am actually quite happy with the current performance and how it works for us, especially with the possibility to skip not needed updates so heavily used components don't use CPU time.

I also don't see any possibility of "selling" an app to our clients that does not show loading progress. So I need to have this in our versions.

We also figured out that we need manual service worker update triggering to be able to forcefully unregister the service worker. Both of which will need to change in the javascript code. I did not look at your latest changes for event handlers but I suppose there is still no way to message the services worker and run code on its behalf? This is more or less how I was implementing dynamic extensions for the service worker (for notifications but also for other things).

**Comment by maxence-charriere** [comment]
@oderwat 

```go
	app.Div().Body(
		app.Customizable("svg").XMLNS("http://www.w3.org/2000/svg").Class("icon", "icon-tabler",
			"icon-tabler-arrow-narrow-right").Attr("width", "24").Attr("height", "24").Attr("viewBox", "0 0 24 24").
			Attr("stroke-width", "1.5").Attr("stroke", "#4338CA").Attr("fill", "none").Attr("stroke-linecap", "round").
			Attr("stroke-linejoin", "round").Body(
			app.Customizable("path").XMLNS("http://www.w3.org/2000/svg").Attr("stroke", "none").Attr("d", "M0 0h24v24H0z").Attr("fill", "none"),
			app.Customizable("line").XMLNS("http://www.w3.org/2000/svg").Attr("x1", "5").Attr("y1", "12").Attr("x2", "19").Attr("y2", "12"),
			app.Customizable("line").XMLNS("http://www.w3.org/2000/svg").Attr("x1", "15").Attr("y1", "16").Attr("x2", "19").Attr("y2", "12"),
			app.Customizable("line").XMLNS("http://www.w3.org/2000/svg").Attr("x1", "15").Attr("y1", "8").Attr("x2", "19").Attr("y2", "12"),
		),
	),
```

Just replace `Elem` by `Customizable` or `ElemSC` by `SelfClosingCustomizable`

For the other things:
- Update skip is the next thing I'm going to work on. I feel like the skip in the PR you sent is too hacky. I want to refactor how the interaction with the engine work in order to support this in a proper way. I also want to clean up that engine part.
- Loading progress is a must. I also want this for my projects

**Comment by oderwat** [comment]
Sounds and looks good! But why `Customizable` I thought `Elem` is quite an elegant name for what it does :). Those things should be short to make that kind of code more readable and for this functionality in special, the "name" does count so much more than the name of the method. I would maybe even call it just "C" and "CS" in my libraries ;-)

**Comment by oderwat** [comment]
Well, I usually prefer code readability and ease of use over such concerns. I need the job to be done. As this will mostly impact generated code I don't care too much though. It still feels wrong to me to reason with 'more annoying to type'. It is simply not possible to extend the package with your own types in Go and using `raw()` would be worse in my eyes. Making something harder to type also does not change the risk in that case. Feels a bit like you still do not want such functionality in the first place. Calling it "Elem()" was because it does that., creating an Element. "Customizable" could mean anything and sounds like you have to do something "after" using it. To customize it and that is just not what it is about.

**Comment by maxence-charriere** [comment]
@oderwat I changed my mind and called them `Elem` and `SelfClosingElem`

**Comment by maxence-charriere** [comment]
@oderwat I took ElemSelfClosing. Not fond of abbreviations. Could you confirm that this branch work with your projects? I'd like to move forward and merge this :).

**Comment by oderwat** [comment]
I tested it with two of my bigger projects and there is a problem related to node updating.

In both of the following examples, the class is not replaced. In the first example all of the divs in the range are rendered green but only the first one should have this class.

image

```go
Body(
	app.Div().Class("text-red-400").Body(
		app.Range(c.history).Slice(func(idx int) app.UI {
			if idx == len(c.history)-1 {
				return app.Div().Class("text-green-600").Text(c.history[idx])
			} else {
				return app.Div().Text(c.history[idx])
			}
		}),
		app.Div().Body(
			app.Span().Class("text-black").Text(c.text),
			app.Span().Class("text-blue-500").Text(predict),
			app.Sup().Class("text-blue-300").Text(predictNr),
		),
	),
),
```

This second example renders the table after loading with blue text!

image

```go
func (c *SortableTable) Render() app.UI {
	dbg.Log()
	if c.rows == nil {
		dbg.Log("c.rows is nil")
		return app.Div().Class("text-blue-500").Text("Loading...")
	}
	// there seems to be a bug (problem?) when this renders a div first and then updates to render a table
	// so I added a div here and it works. Need to check what is going on!
	return app.Div().Body(app.Table().Class("border border-slate-200 p-4").Body(
		app.THead().Body(
			app.Tr().Body(
				app.Range(c.heads).Slice(func(col int) app.UI {
					return app.Th().OnClick(c.ReSort(col), col).Class("text-center border border-slate-300 p-2 cursor-pointer").Body(
						app.Div().Body(
							app.Text(c.heads[col]),
						),
					)
				}),
			),
		),
		app.TBody().Body(
			app.Range(c.rows).Slice(func(row int) app.UI {
				return app.Tr().Body(
					app.Range(c.heads).Slice(func(col int) app.UI {
						return app.Td().Class("border border-slate-300 p-2", c.class[col]).Body(
							app.Text(c.rows[row][col]),
						)
					}),
				)
			}),
		),
	))
}
```

The second example also contains some bug descriptions I found earlier. When I first return a div and after that, I return a table the browser will hang endlessly. It seems like `Render` only works if the root element between renders is of the same node type. I did not report it earlier because I am not sure if it is supposed to work.

For reference: The commit hash of the version I tested is f13d6ea9e8b0aed68e7f814b837e2fc6f88a20b5

**Comment by maxence-charriere** [comment]
@oderwat might be because of this: https://stackoverflow.com/questions/33239464/javascript-delete-object-property-not-working
I changed it back to just removing the attribute. Can you test that it is working as expected?

**Comment by oderwat** [comment]
This indeed fixes the problem I have. What about the other (dead loop) problem mentioned in the second example? Do you care to fix that with the same commit?

Besides that, I applied my other PRs and checked two more projects and could not yet detect another problem. So I think this is a go.

Do you really want to rename `Mounted()` to `IsMounted()` this is the only breaking change and may affect some people? It affects all our team's code and even public packages which would need to get a new version (if I would care) just because of an unimportant name change.  Not hard to fix but I (again) don't see why `IsMounted()` should be better than `Mounted`. I even feel a bit like `IsMounted()` checks for a type. But I may make this up.

**Comment by maxence-charriere** [comment]
That is a good catch, i did not realize Mounted was exported. I ll change it back

**Comment by maxence-charriere** [comment]
> But the second example also contains a description of a problem I found earlier. When I first return a div and after that, I return a table the browser will hang endlessly. It seems like Render only works if the root element between renders is of the same node type. I did not report it earlier because I am not sure if it is supposed to work.

is this problem was introduced with the change of this PR?

**Comment by oderwat** [comment]
> is this problem was introduced with the changes of this PR?

No. I did not work with earlier versions either.

**Comment by maxence-charriere** [comment]
the second issue seems to be component oriented. Il try to address this in another branch

**Comment by oderwat** [comment]
We still use that branch as the basis for our internal fork and it seems to work very well.

**Comment by maxence-charriere** [comment]
I m going to create a v9.6 branch where I'll merge the latest things I m working on. I'll soon take holiday where I will have some time to work on some go-app-related stuff. v9.6 will be released somewhere around the end of July/ beginning of August.

**Pull request closed without merging**
