### PR TITLE
Broader use of formatted string arg and generated documentation overhaul

### PR DESCRIPTION
**Pull request by maxence-charriere**

### CODE REVIEW

**Comment by oderwat** [comment]
I wonder about the use of "that" instead of "this" in all the wording corrections.

"that controls the text direction of its content, overriding other directional settings." vs
"this controls the text direction of its content, overriding other directional settings."

I would also prefer the more concise but still valid:

"controls the text direction of its content, overriding other directional settings."

**Comment by maxence-charriere** [comment]
This is how it looks when generated:
```go
// Returns an HTML element that controls the text direction of its content, overriding other directional settings.
func Bdo() HTMLBdo {
	e := &htmlBdo{
		htmlElement: htmlElement{
			tag:           "bdo",
			isSelfClosing: false,
		},
	}

	return e
}
```

**Comment by oderwat** [comment]
Oh, I see. Sorry for wasting your time!

**Comment by maxence-charriere** [comment]
No worries, your input is always valuable.

**Pull request merged**
