### PR TITLE
parser substring to struct by index and app tag

### PR DESCRIPTION
**Pull request by antboard**
I put some information in the url. After routing with regular expressions, I can’t get the latest url, so I think about assigning sub-strings to structure variables when routing. This is like backend routing.

### CODE REVIEW

**Comment by maxence-charriere** [comment]
Hey hello, sorry to come back that late on this. I just moved to another country which made me pretty busy recently.

I'm not sure to properly understand the problem. Could you paste an example of the Routes with regexp you are using, what are you missing and/or expecting?

It would really help me properly review this PR.
Thanks.

**Comment by antboard** [comment]
Thanks for replying, I remember you were in Japan before.

here is the demo:

```
package main

import (
	"github.com/maxence-charriere/go-app/v7/pkg/app"
	"log"
)

//===========================================
type Article struct {
	app.Compo
}

func (a *Article) Render() app.UI {
	return app.Div().Body(
		app.A().Href("/md/22222").Text("test href"),
	)
}

//============================================

type Text struct {
	app.Compo
	URL string `app:"0"`
	ID  string `app:"1"`
}

func (t *Text) Render() app.UI {
	// i want to parse url, get id value, but the url is wrong
	url := app.Window().URL().String()
	return app.Div().Body(
		app.Div().Text(t.URL),
		app.Div().Text(url),
	)
}

func main() {
	log.Println("hello")
	app.RouteWithRegexp("/md/(.*)", &Text{})
	app.Route("/article", &Article{})
	app.Run()
}
```

I want to change Regular expression, because I find a bug when I click the href.  
but I'm not sure which is good ,  such as gin, They are not using standard regular expressions. 
default,  regular expression can check match and parse to []string, 
I hope that the application layer can easily communicate with the framework layer, and I need a way to pass variables to the structure. 
like the code

```
urls := regexp.FindStringSubmatch(path)
if len(urls) >n {
  t.URL = urls[0]
  t.ID = urls[1]
}
```

The method of using labels does not seem very professional. It's just simple.

**Comment by maxence-charriere** [comment]
This is not a bug. What is happening here is that the `Text` component has its last rendering before the URL is modified.

Here are the order events happen:
1. Link is clicked
2. Route is checked
3. Component Text is picked and rendered
4. URL is overloaded
5. (where you should update the URL)

What you need to do is to deal with the component lifecycle by looking for the [OnNav](https://github.com/maxence-charriere/go-app/wiki/Components#onnav) event.

```go
func (t *Text) OnNav(ctx app.Context, u *url.URL) {
	t.URL = app.Window().URL().String()
	t.Update()
}
```

**Comment by antboard** [comment]
I get it thanks

**Pull request closed without merging**
