### PR TITLE
v9.6.0

### LINKED ISSUE #753: LocalDir ResourceProvider does not find /web relative to executable
Hi there. Just getting started with my first go-app project, and I am finding that even though the docs state this:

(https://go-app.dev/static-resources)

> static resources are to be put into a directory called web, by default located next to the [server](https://go-app.dev/architecture#server) executable

... I am finding that the implementation of `LocalDir()` (default) actually expects the "web" directory to be relative to the current working directory as opposed to the location of the executable. If I run the executable from a different location, regardless of the web directory being right next to it, the resources are not found. In my own code I have had to implement a modified version that does the following:

```go
func LocalResourceDir() app.ResourceProvider { 
	path, _ := os.Executable() 
	path = filepath.Dir(path) 
	return resourcesFS{ 
		Handler: http.FileServer(http.Dir(path)), 
	} 
} 

type resourcesFS struct { 
	http.Handler 
} 

func (resourcesFS) Package() string { return "" } 
func (resourcesFS) Static() string  { return "" } 
func (resourcesFS) AppWASM() string { return "/web/app.wasm" } 
```

Is this something the `LocalDir()` should support? Or should the documentation be updated to reflect the current behaviour?

Thanks!

### PR DESCRIPTION
**Pull request by maxence-charriere**
## Summary

- Go requirement bumped to Go v1.18
- Custom elements (`Elem` and `ElemSelfClosing`)
- Prevent component update
- Engine optimization that ensure a component update is done once per frame cycle
- Customizable app-worker.js template
- Some documentation tweak

## Fixes
- fix #753

### CODE REVIEW

**Comment by maxence-charriere** [comment]
@oderwat I refactored the engine. There are so far no regressions on my projects. This also come with the `context.PreventUpdate()` method that should solve https://github.com/maxence-charriere/go-app/pull/711.
The mechanism here is that if a component update is prevented, parent components will not be updated following a emit.

Could you check if this work as intended?

**Comment by oderwat** [comment]
@maxence-charriere I made some first checks and found that one of my test components did not work the same way and was crippeld. This one uses "ctx.PreventUpdate()" and starts an `app.Async()` that uses a "debouncer" to prevent backend calls for every key press. When that debouncer triggers, it uses `component.Update()` for updating the component. With my `ctx.SkipAllUpdates()` it works. When I use `ctx.PreventUpdate()`, it mostly does not work (the update is not done).

When I use a `ctx.Dispatch()` construct and do the update inside it still does not work. If I do it inside of a `ctx.Defer()` construct, it does work.

```go
	ctx.Defer(func(_ app.Context) {
		c.Update()
	})
```

I had no time to look at your code but I suspected that it depends on which cycle the Update is called in and added a `time.Sleep()` before the update and it worked. So I guess your way to prevent the update will not get overridden when `component.Update()` is being called in the same cycle. The defer and the delayed execution skip to the next cycle and don't prevent the update. I would prefer that the manually triggered update does force the update.

P.S.: I still need to check some other projects and will come back with my findings there.

**Comment by maxence-charriere** [comment]
@oderwat made a small change, can you try again?

**Comment by oderwat** [comment]
Works!

**Comment by maxence-charriere** [comment]
@oderwat Thank you. Yep let me know if it has the expected behavior and if an update is effectively canceled.

**Comment by oderwat** [comment]
I was going to all code that skipped events, and stuff works as I expect it to work. I would say those changes are fine. I also did not find side effects at other places.

**Comment by oderwat** [comment]
While checking the behavior of the loading progress (which also would need a custom formatting string, IMHO), I stumbled on an older comment of mine, which is still true: If you enable auto compression through middleware for java-script files, the app does not trigger up-updates anymore. It does show the readiness of the new worker in the console, but it seems not to transport this into the `AppUpdateAvailable.` I did not debug why that is.

**Comment by oderwat** [comment]
I copied and edited the middleware to emit an `X-Content-Length-Uncompressed` header. I think that if you just make a slight change to the code so that we can send an extra header, it would go a long way!

**Comment by maxence-charriere** [comment]
@oderwat Thanks for the feedback I'll be looking at improving the loader next. In the meantime can you test the latest version of this branch?

I made those optimizations:
- order updates from closest from root to farthest
- ensure that component updates are done only once per frame
- js event only updates the nearest component

I'd like to make sure that does not break anything for you.

**Comment by oderwat** [comment]
I build all of our apps and tested them. No regressions were found.

**Comment by maxence-charriere** [comment]
@oderwat made some improvements on the loader size.

- Loader text can be customized with `Handler.LoadingLabel`:
  ```go
	// The text displayed while loading a page. Load progress can be inserted by
	// including "{progress}" in the loading label.
	//
	// DEFAULT: "{progress}%".
	LoadingLabel string
  ```
- You can specify the HTTP header to get the wasm file content-length with `Handler.WasmContentLengthHeader `:
  ```go
 	// The HTTP header to retrieve the WebAssembly file content length.
	//
	// Content length finding falls back to the Content-Length HTTP header when
	// no content length is found with the defined header.
	WasmContentLengthHeader string
  ```

Let me know if it works for you.

**Comment by oderwat** [comment]
That is fine! I have another problem that could easily be solved by adding something similar: Modifying the service worker. Maybe you can make the name or the content customizable?

**Comment by maxence-charriere** [comment]
I don’t get what is the problem with the service worker. This is a bit tricky to touch since it can mess with a lot of things.

**Comment by oderwat** [comment]
I know, but I want to be able to change how it works. For example, to change how the reacts to the user selecting an option from the push notification and how the app reacts to that. For this, you need to have a message handler between the sever worker and the app, One of my more wanted features would be to tell the service-worker to actively check for an update (like on key press in an app) and to react on that. Another thing would be to kill this or other service workers and reload the page, which is not possible from the "outside",

**Comment by maxence-charriere** [comment]
I still don’t understand how you propose to solve this.

**Comment by oderwat** [comment]
I thought of a way to change `appWorkerJS` to something the implementation can supply by adding an indirection for what is being used by the template. `app.AppWorkerJS=appWorkerJS` so the developer can change it to something else (or add onto it)  to avoid forking all of go-app to have a different worker. You can do most other stuff already by just adding `app.RawHeaders`, but currently you can't modify/access the service worker at all. Maybe having such indirection for all of the static scripts would be nice to have and is possible at a very low cost. Currently, one needs to make a fork or at least a local clone and run `make gen` all the time to do experiments and keep a fork up to date to implement more specialized behavior. This also needs watching changes in another file system path to trigger recompilations (when using a watcher).

**Comment by maxence-charriere** [comment]
If replacing the worker is what you need, why not overriding the “/app-worker.js” endpoint with a http handler?

**Comment by oderwat** [comment]
Yes, but then one has to get the standard code from somewhere, which may also change. I find it easier (and slightly more save) to take the existing code, apply a patch and use that one so that stuff like `const resourcesToCache = {{.ResourcesToCache}};` is still added by Go-App.

**Comment by maxence-charriere** [comment]
@oderwat is your suggestion is adding a string like 
```go
type Handler struct {
    // JavaScript code to extend app-worker.js.
    AppWorkerExtension string
}
```

and inject it into the app-worker.js template with `{{.AppWorkerExtension}}` at the end?

**Comment by oderwat** [comment]
I would prefer that it replaces the original and that one has access to the original one.

```go
type Handler struct {
    // JavaScript code for the app-worker.js. If empty, it defaults to using the constant AppWorkerJS
    AppWorker string
}
```

This way, you can extend, modify or replace the app-worker.js code.

**Pull request merged**
