### PR TITLE
Custom public folder and app.wasm

### PR DESCRIPTION
**Pull request by gabstv**
Adds the ability to set a custom path for the public files folder instead of using the current working directory + `/web`. Custom URL prefix (replaces `/web/`) and WASM (replaces `cwd/app.wasm`):

```go
package main

import (
	"fmt"
	"net/http"
	"os"
        "path"

	"github.com/rs/zerolog/log"
	"github.com/urfave/cli"
	"github.com/maxence-charriere/go-app/v6/pkg/app"
)

func main() {
	cla := cli.NewApp()

	cla.Flags = []cli.Flag{
		cli.StringFlag{
			Name:   "http-listen, http",
			EnvVar: "HTTP_LISTEN",
			Value:  ":8080",
		},
		cli.StringFlag{
			Name:   "basedir",
			EnvVar: "BASEDIR",
			Value:  "./pub",
		},
	}

	cla.Action = serve

	if err := cla.Run(os.Args); err != nil {
		if e, ok := err.(*cli.ExitError); ok {
			fmt.Fprintf(os.Stderr, e.Error())
			os.Exit(e.ExitCode())
		}
		fmt.Fprintf(os.Stderr, err.Error())
		os.Exit(1)
	}
}

func serve(c *cli.Context) error {
	wd := c.String("basedir")
	l := c.String("http-listen")
	log.Warn().Str("basedir", wd).Msgf("Starting HTTP Server at %q", l)

	h := &app.Handler{
        Title:  "Hello Demo",
		Author: "Gabriel Ochsenhofer",
		Styles: []string{"/res/css/style.css"},
		Scripts: []string{"https://use.fontawesome.com/releases/v5.12.1/js/all.js"},
                WASMPath: path.Join(c.String("basedir"), "app.wasm"),
                PublicURLPrefix: "/res/",
                PublicPathPrefix: c.String("basedir"),
	}

	if err := http.ListenAndServe(l, h); err != nil {
		log.Error().Err(err).Msg("server closed")
		return err
	}
	return nil
}

```

### CODE REVIEW

**Comment by maxence-charriere** [comment]
I implemented something like this at start and then I removed it because allowing different folder structure result in multiple way to use the package and was more hard to document.

I m not against have it back but I would like to understand what are the scenario where you would like to change those path.

**Comment by gabstv** [comment]
I did this because I could pass a docker volume for the public css/js files, in development they are compiled multiple times using `dart-sass` so I thought it was more convenient to make it customizable for my tests/builds.

**Comment by maxence-charriere** [comment]
I see. I want to take the weekend to think about how I'd like to have it done.
I'm also thinking of having an s3 or google storage bucket in order to do fewer requests when it is deployed on a cloud function.

Thanks for the feedback.

**Comment by maxence-charriere** [comment]
Hey @gabstv ,
I had been working on this issue this week.

you can see the PR here => https://github.com/maxence-charriere/go-app/pull/360

So it is a little bit different than the one you got here. You can set a `RootDir` in the `Handler`. The root directory can be:
-  a custom local path (absolute or relative to the server binary) 
- a remote location such as an S3 bucket (I wanted this in order to reduce count when it is deployed on a cloud function)

The reason why I did not want 2 variables is that I wanted to keep a single resource pattern:
- `/*`:  resources that make the package work (the one served by the handler + app.wasm)
- `/web/*`: static files

That way it was easier to adapt the remote logic and when you understand how it works, the pattern does not change depending on the environment.

Let me know if it solves your problem.

**Comment by gabstv** [comment]
I like your solution! I also prefer to use less variables when possible.

**Pull request closed without merging**
