### PR TITLE
Super simple replacement of `text/template`

### PR DESCRIPTION
**Pull request by oderwat**
I wanted to test what happens when `text/template` gets removed in regard to compilation using TinyGo.

### CODE REVIEW

**Comment by maxence-charriere** [comment]
What benefit you got with this?

**Comment by oderwat** [comment]
It's even closer to making it compiling with TinyGo. But as I wrote in #679 it is still not fully possible.

**Review by maxence-charriere — COMMENTED** [review]
I'm not sure about this. Here, the use of `text/html` brings a layer of error check about whether the file is correctly formatted.

I'm wondering about the gain in terms of binary size. It may also require improving the unit tests for `Handler` functions since we would lose an error check.

I want to avoid spending time on strings bug hunting when I'm making changes to those templates.

**Comment by maxence-charriere** [comment]
I changed CI in the repo but I don't see why checks are not launched on this branch. Might require that you update from master 🤔.

**Comment by oderwat** [comment]
This is not a PR meant to be merged (yet). This just replaces the `text/template` dependency to hopefully be able to compile a go-app application WASM part with Tiny-Go which would decrease the WASM size most likely by a lot (100 times is possible). Currently, it can't compile because of the dependencies to the reflection code used by `text/template`. Getting rid of these it seems to be possible to compile. I did not check what else needs to be done. As mentioned it complains about a missing routine in `os` right now.  Besides that it really does not need the template from my perspective :)

**Comment by maxence-charriere** [comment]
Yes, just trying to evaluate the pros and what it would take. Could definitely accept this if it is for binary size improvements. Tinygo is not on my priority list for now but anything that can improve the current binary size is.

**Comment by oderwat** [comment]
TinyGo actually should be one. It is like the current WASM uses 8 MB. The TinyGo version most likely about 400 KB. 

See this. I am not at work so I can't grab my number: https://dev.bitolog.com/minimizing-go-webassembly-binary-size/

**Comment by maxence-charriere** [comment]
> In other words – TinyGo is a Go compiler, focused on creating small binaries. Since TinyGo does not aim to compile any possible Go program, it lacks some language and packages support. In other words, this means that you might need to modify your code in order for it to be compiled by TinyGo.

This is the exact reason why it is not on my priority list.

**Comment by oderwat** [comment]
It is on mine. And for a reason: All WASM stuff just fails to be used in production if the code is like 13 MB download upfront. We can compress it down to 3,5 MB but that is still a lot. So when I can compile it with TinyGo and shrink it to just some hundred kilobytes, it becomes a reasonable replacement for javascript.

**Comment by maxence-charriere** [comment]
Ok. Well, I'm not against this PR then but want to see if we can do better testing.

**Comment by mar1n3r0** [comment]
> template

Rather than completely getting rid of text/template we can use https://github.com/valyala/fasttemplate which does not rely on reflection and text/template. Btw how do you test the changes in go-app locally?

**Comment by oderwat** [comment]
@mar1n3r0 I personally would not use any (external) extension for the use case in go-app which is just replacing some strings. But as I said. This PR was just made to see if I compile afterward with TinyGo and it does not (even though it may be closer).

**Comment by mar1n3r0** [comment]
> @mar1n3r0 I personally would not use any (external) extension (dependency) for the use case in go-app which is just replacing some strings. But as I said. This PR was just made to see if I compile afterward with TinyGo and it does not (even though it may be closer).

@maxence-charriere is right about integrity and type safety when compiling the templates. Anyway I got to the SetEnv error you have reached. I guess we can keep on digging in the main issue until we figure it out. It's very close to working now.

**Comment by mar1n3r0** [comment]
> > @mar1n3r0 I personally would not use any (external) extension (dependency) for the use case in go-app which is just replacing some strings. But as I said. This PR was just made to see if I compile afterward with TinyGo and it does not (even though it may be closer).
> 
> @maxence-charriere is right about integrity and type safety when compiling the templates. Anyway I got to the SetEnv error you have reached. I guess we can keep on digging in the main issue until we figure it out. It's very close to working now.

You are also right that for the sake of testing Tinygo twe can skip the templates in the tests.

**Comment by oderwat** [comment]
So is the app you compiled splitting out the server part by using another build tag? And does it use `net/http` or not?

I am going to test our apps later on. But to me a difference of 3 MB is already pretty cool.

**Comment by mar1n3r0** [comment]
> 

It's the original hello example without any changes except commenting out the SetEnv part. 3MB is way less than we expected based on vecty where the reduction was 10 times.

**Comment by maxence-charriere** [comment]
@oderwat, just a bit out of subject, I try to make my CI work for PR like yours. Is your branch up to date with master?

**Comment by oderwat** [comment]
Yes. Just double-checked.

**Comment by maxence-charriere** [comment]
Okay folks, so I gave a try to support tinygo...
Good new is that I was able to make it compile.
Bad new is that it does not load in the browser.

Can have a look there => https://github.com/maxence-charriere/go-app/pull/682

**Pull request closed without merging**
